# Command: /work_on_issue
description = "Starts work on a given GitHub issue URL by creating a branch and confirming the plan."
prompt = """
Please start working on the issue at the following URL: {{args}}
use context7

Follow these steps:
1. Read the issue details from the URL.
2. Confirm with me that you understand the task by summarizing it.
3. Create a new branch for this issue using the format `type/issue-number/short-description`.
4. Checkout the new branch.
5. Start implementation.
6. Once the implementation is complete, create a pull request.
"""